spring:
  config:
    import: secrets.yml
  jpa:
    properties:
      hibernate:
        show_sql: true # DDL, DML 쿼리 모두 출력
        format_sql: true # 쿼리를 알기 쉽게 보여줌
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      apache:
        coyote:
          http11: debug